"use client";
import * as React from "react"
import Link from "next/link"
import { ScrollArea } from "@/components/ui/scroll-area"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Label } from "@/components/ui/label"
import { Switch } from "@/components/ui/switch"
import {
  Sheet,
  SheetClose,
  SheetContent,
  SheetDescription,
  SheetFooter,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/components/ui/sheet"
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip"
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectLabel,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import { Icons } from "@/components/shared/icons"
import { SubmitButton } from "./submit-modal";
 
export function DrawerDialogDemo() {
  return (
    <Sheet>
      <SheetTrigger asChild>
        <Button variant="default">Adjust campaign</Button>
      </SheetTrigger>
      <SheetContent side={'bottom'} className="px-16">
        <ScrollArea>
        <SheetHeader>
          <div className="mt-2 px-5">
          <SheetTitle>Adjust keyword filters</SheetTitle>
          <SheetDescription>
            {"BuzzDaddy detects forums & posts using these configurable keywords."}
          </SheetDescription>
          </div>
        </SheetHeader>
        <div className="grid gap-4 py-8">
          <p>Add keywords here (input + pills with remove x) Ai autogenerated by default + button to suggest more.</p>
        </div>
        <SheetFooter className="w-full">
          <SheetClose asChild>
            <SubmitButton/>
          </SheetClose>
        </SheetFooter>
        </ScrollArea>
      </SheetContent>
    </Sheet>
  )
}

  // Define selection options for branches
  const branchOptions = [
    { value: "ehst", text: "Feature" },
    { value: "cst6", text: "Bug" },
    { value: "csgt", text: "New Project" },
  ];